# Form implementation generated from reading ui file '.\filter_check.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_filter_check(object):
    def setupUi(self, filter_check):
        filter_check.setObjectName("filter_check")
        filter_check.resize(303, 91)
        filter_check.setStyleSheet("background-color: rgb(50, 50, 50)")
        self.horizontalLayout = QtWidgets.QHBoxLayout(filter_check)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=filter_check)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMinimumSize(QtCore.QSize(50, 30))
        self.checkBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.checkBox.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(51, 55, 57);\n"
"font: 63 15pt \"Yu Gothic UI Semibold\";\n"
"\n"
"border-radius: 25%\n"
"\n"
"\n"
"")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)

        self.retranslateUi(filter_check)
        QtCore.QMetaObject.connectSlotsByName(filter_check)

    def retranslateUi(self, filter_check):
        _translate = QtCore.QCoreApplication.translate
        filter_check.setWindowTitle(_translate("filter_check", "Form"))
        self.checkBox.setText(_translate("filter_check", "CheckBox"))
