# Form implementation generated from reading ui file '.\filter_window_UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_filter_window(object):
    def setupUi(self, filter_window):
        filter_window.setObjectName("filter_window")
        filter_window.resize(212, 338)
        filter_window.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.verticalLayout = QtWidgets.QVBoxLayout(filter_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=filter_window)
        self.scrollArea.setMinimumSize(QtCore.QSize(200, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 198, 298))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.v_lay = QtWidgets.QVBoxLayout()
        self.v_lay.setObjectName("v_lay")
        self.verticalLayout_2.addLayout(self.v_lay)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_button = QtWidgets.QPushButton(parent=filter_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setMinimumSize(QtCore.QSize(30, 20))
        self.cancel_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.yes_button = QtWidgets.QPushButton(parent=filter_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yes_button.sizePolicy().hasHeightForWidth())
        self.yes_button.setSizePolicy(sizePolicy)
        self.yes_button.setMinimumSize(QtCore.QSize(30, 20))
        self.yes_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.yes_button.setObjectName("yes_button")
        self.horizontalLayout.addWidget(self.yes_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(filter_window)
        QtCore.QMetaObject.connectSlotsByName(filter_window)

    def retranslateUi(self, filter_window):
        _translate = QtCore.QCoreApplication.translate
        filter_window.setWindowTitle(_translate("filter_window", "Form"))
        self.cancel_button.setText(_translate("filter_window", "Отмена"))
        self.yes_button.setText(_translate("filter_window", "Да"))
