# Form implementation generated from reading ui file 'Wallet_Ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(864, 599)
        Form.setStyleSheet("background-color: rgb(35, 38, 39);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.pushButton_5.setStyleSheet("color:rgb(223, 228, 229);\n"
"font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(51, 55, 57);\n"
"border-radius: 25%\n"
"\n"
"")
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/angle-left-b.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(500, 60))
        self.label.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(44, 47, 49);\n"
"border-radius: 10%;\n"
"font: 63 20pt \"Yu Gothic UI Semibold\";\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_10 = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 100))
        self.label_10.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_10.setStyleSheet("color:rgb(223, 228, 229);\n"
"font: 63 16pt \"Yu Gothic UI Semibold\";\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.balance_label = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.balance_label.sizePolicy().hasHeightForWidth())
        self.balance_label.setSizePolicy(sizePolicy)
        self.balance_label.setMinimumSize(QtCore.QSize(0, 100))
        self.balance_label.setStyleSheet("color:rgb(223, 228, 229);\n"
"font: 63 16pt \"Yu Gothic UI Semibold\";\n"
"\n"
"")
        self.balance_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.balance_label.setObjectName("balance_label")
        self.horizontalLayout_6.addWidget(self.balance_label)
        self.label_12 = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 100))
        self.label_12.setStyleSheet("color:rgb(223, 228, 229);\n"
"font: 63 16pt \"Yu Gothic UI Semibold\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setMinimumSize(QtCore.QSize(300, 60))
        self.label_2.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(44, 47, 49);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setIndent(20)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 60))
        self.label_3.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(60, 65, 67);\n"
"border-radius:1 pt;\n"
"\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.replenish_300 = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replenish_300.sizePolicy().hasHeightForWidth())
        self.replenish_300.setSizePolicy(sizePolicy)
        self.replenish_300.setMinimumSize(QtCore.QSize(150, 0))
        self.replenish_300.setMaximumSize(QtCore.QSize(200, 60))
        self.replenish_300.setStyleSheet("color:rgb(223, 228, 229);\n"
"border: 5px solid  rgb(60, 65, 67);\n"
"\n"
"background-color: rgb(103, 116, 120);\n"
"font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"\n"
"")
        self.replenish_300.setAutoDefault(False)
        self.replenish_300.setObjectName("replenish_300")
        self.horizontalLayout_2.addWidget(self.replenish_300)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setMinimumSize(QtCore.QSize(300, 60))
        self.label_4.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(44, 47, 49);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_4.setIndent(20)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 60))
        self.label_5.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(60, 65, 67);\n"
"\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.replenish_500 = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replenish_500.sizePolicy().hasHeightForWidth())
        self.replenish_500.setSizePolicy(sizePolicy)
        self.replenish_500.setMinimumSize(QtCore.QSize(150, 0))
        self.replenish_500.setMaximumSize(QtCore.QSize(200, 60))
        self.replenish_500.setStyleSheet("color:rgb(223, 228, 229);\n"
"border: 5px solid rgb(60, 65, 67);\n"
"\n"
"background-color: rgb(103, 116, 120);\n"
"font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"\n"
"")
        self.replenish_500.setAutoDefault(False)
        self.replenish_500.setObjectName("replenish_500")
        self.horizontalLayout_3.addWidget(self.replenish_500)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setMinimumSize(QtCore.QSize(300, 60))
        self.label_6.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(44, 47, 49);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_6.setIndent(20)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(200, 60))
        self.label_7.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(60, 65, 67);\n"
"\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.replenish_1000 = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replenish_1000.sizePolicy().hasHeightForWidth())
        self.replenish_1000.setSizePolicy(sizePolicy)
        self.replenish_1000.setMinimumSize(QtCore.QSize(150, 0))
        self.replenish_1000.setMaximumSize(QtCore.QSize(200, 60))
        self.replenish_1000.setStyleSheet("color:rgb(223, 228, 229);\n"
"border: 5px solid  rgb(60, 65, 67);\n"
"\n"
"background-color: rgb(103, 116, 120);\n"
"font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"\n"
"")
        self.replenish_1000.setAutoDefault(False)
        self.replenish_1000.setObjectName("replenish_1000")
        self.horizontalLayout_4.addWidget(self.replenish_1000)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setMinimumSize(QtCore.QSize(300, 60))
        self.label_8.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(44, 47, 49);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";")
        self.label_8.setIndent(20)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setMaximumSize(QtCore.QSize(100, 60))
        self.label_9.setStyleSheet("color:rgb(223, 228, 229);\n"
"background-color: rgb(60, 65, 67);\n"
"border-radius:1 pt;\n"
"\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";")
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setIndent(0)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.replenish = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replenish.sizePolicy().hasHeightForWidth())
        self.replenish.setSizePolicy(sizePolicy)
        self.replenish.setMinimumSize(QtCore.QSize(150, 0))
        self.replenish.setMaximumSize(QtCore.QSize(200, 60))
        self.replenish.setStyleSheet("color:rgb(223, 228, 229);\n"
"border: 5px solid  rgb(60, 65, 67);\n"
"\n"
"background-color: rgb(103, 116, 120);\n"
"font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"\n"
"")
        self.replenish.setAutoDefault(False)
        self.replenish.setObjectName("replenish")
        self.horizontalLayout_5.addWidget(self.replenish)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_3.addItem(spacerItem14)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Пополните баланс "))
        self.label_10.setText(_translate("Form", "Баланс :"))
        self.balance_label.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "₽"))
        self.label_2.setText(_translate("Form", "Добавить 300₽"))
        self.label_3.setText(_translate("Form", "300₽"))
        self.replenish_300.setText(_translate("Form", "Пополнить "))
        self.label_4.setText(_translate("Form", "Добавить 500₽"))
        self.label_5.setText(_translate("Form", "500₽"))
        self.replenish_500.setText(_translate("Form", "Пополнить "))
        self.label_6.setText(_translate("Form", "Добавить 1000₽"))
        self.label_7.setText(_translate("Form", "1000₽"))
        self.replenish_1000.setText(_translate("Form", "Пополнить "))
        self.label_8.setText(_translate("Form", " Произвольная сумма"))
        self.replenish.setText(_translate("Form", "Пополнить "))
