# Form implementation generated from reading ui file 'imageButton.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(222, 361)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background-color: rgb(27, 29, 30);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_button = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_button.sizePolicy().hasHeightForWidth())
        self.image_button.setSizePolicy(sizePolicy)
        self.image_button.setMinimumSize(QtCore.QSize(200, 225))
        self.image_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.image_button.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.image_button.setStyleSheet("font: 11pt \"Arial\";\n"
"color: rgb(243, 243, 243);")
        self.image_button.setText("")
        self.image_button.setIconSize(QtCore.QSize(50, 50))
        self.image_button.setFlat(True)
        self.image_button.setObjectName("image_button")
        self.verticalLayout.addWidget(self.image_button)
        self.title_listWidget = QtWidgets.QListWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_listWidget.sizePolicy().hasHeightForWidth())
        self.title_listWidget.setSizePolicy(sizePolicy)
        self.title_listWidget.setMinimumSize(QtCore.QSize(200, 50))
        self.title_listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title_listWidget.setStyleSheet("color:rgb(223, 228, 229);\n"
"font: 14pt \"Arial\";")
        self.title_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.title_listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.title_listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.title_listWidget.setObjectName("title_listWidget")
        self.verticalLayout.addWidget(self.title_listWidget)
        self.prise_listWidget = QtWidgets.QListWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prise_listWidget.sizePolicy().hasHeightForWidth())
        self.prise_listWidget.setSizePolicy(sizePolicy)
        self.prise_listWidget.setMinimumSize(QtCore.QSize(200, 50))
        self.prise_listWidget.setStyleSheet("color:rgb(223, 228, 229);\n"
"font: 14pt \"Arial\";")
        self.prise_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.prise_listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.prise_listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.prise_listWidget.setObjectName("prise_listWidget")
        self.verticalLayout.addWidget(self.prise_listWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
