# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(400, 300)
        main_window.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(main_window)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stacked = QtWidgets.QStackedWidget(parent=main_window)
        self.stacked.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.stacked.setObjectName("stacked")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stacked.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stacked.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stacked)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "PyEpicGamesStore"))
